apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jlab-storage
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jlab-frontend
spec:
  containers:
  - name: vol-container
    image: centos7
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /var/lib/gwms-frontend/web-area
      name: jlab-storage
  restartPolicy: Never
  volumes:
    - name: jlab-storage
      persistentVolumeClaim:
        claimName: jlab-storage
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
