apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jlab-storage
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jlab-ingress
spec:
  backend:
    serviceName: jlab-frontend
    servicePort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: jlab-frontend
spec:
  containers:
  - name: gwms-fe-docker
    image: aaarora/gwms-fe-docker:latest
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: "/var/lib/gwms-frontend/web-area"
      name: jlab-storage
    ports:
    - containerPort: 80
  restartPolicy: Never
  volumes:
    - name: jlab-storage
      persistentVolumeClaim:
        claimName: jlab-storage
