apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jlab-frontend
  namespace: osg-frontends
spec:
  template:
    metadata:
      labels:
        k8s-app: jlab-frontend
    spec:
      containers:
      - name: jlab-frontend
        image: aaarora/gwms-fe-docker:latest
        volumeMounts:
        - mountPath: /var/lib/gwms-frontend/web-area
          name: jlab-storage
        - mountPath: /etc/grid-security/gwms-frontend
          name: proxycerts-secret
          readOnly: true
        - mountPath: /etc/grid-security/gwms-frontend
          name: vomscerts-secret
          readOnly: true
        resources:
          limits:
            cpu: 4
            memory: 1Gi
          requests:
            cpu: 3
            memory: 1Gi
      restartPolicy: Always
      volumes:
        - name: jlab-storage
          persistentVolumeClaim:
            claimName: jlab-storage
        - name: proxycerts-secret
          secret:
            secretName: proxycerts
        - name:  vomscerts-secret
          secret:
            secretName: vomscerts
